export const HEBREW_TEXTS = {
  COMMON: {
    LOADING: 'טוען...',
    SAVE: 'שמור',
    CANCEL: 'ביטול',
    DELETE: 'מחק',
    EDIT: 'עריכה',
    SEARCH: 'חיפוש',
    FILTER: 'סינון',
    CLEAR: 'נקה',
    CONFIRM: 'אישור',
    BACK: 'חזור',
    NEXT: 'הבא',
    PREVIOUS: 'הקודם',
    SUBMIT: 'שלח',
    CLOSE: 'סגור',
    OPEN: 'פתח',
    YES: 'כן',
    NO: 'לא',
    SUCCESS: 'בוצע בהצלחה',
    ERROR: 'שגיאה',
    WARNING: 'אזהרה',
    INFO: 'מידע',
  },
  NAVIGATION: {
    HOME: 'בית',
    GAMES: 'משחקים',
    CENTERS: 'מוקדים',
    PROFILE: 'פרופיל',
    DASHBOARD: 'לוח בקרה',
    ADMIN: 'ניהול',
    LOGIN: 'כניסה',
    REGISTER: 'הרשמה',
    LOGOUT: 'יציאה',
  },
  GAME: {
    AVAILABLE: 'זמין',
    RENTED: 'מושאל',
    UNAVAILABLE: 'לא זמין',
    DAMAGED: 'פגום',
    LOST: 'אבד',
    RENT_NOW: 'השאל עכשיו',
    RETURN: 'החזר',
    EXTEND: 'הארך',
  },
  RENTAL: {
    PENDING: 'בהמתנה',
    APPROVED: 'אושר',
    REJECTED: 'נדחה',
    ACTIVE: 'פעיל',
    RETURNED: 'הוחזר',
    OVERDUE: 'באיחור',
    CANCELLED: 'בוטל',
  },
  ROLES: {
    USER: 'משתמש',
    COORDINATOR: 'רכז',
    SUPER_COORDINATOR: 'רכז עליון',
    ADMIN: 'מנהל',
  },
} as const